# Publishing Java packages with Maven
name: Publish Development
on:
  push:
    tags:
      - 'v0.0.*'

jobs:
  publish:
#    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && endsWith(github.event.base_ref, '/dev')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      tag: ${{ steps.extract_tag.outputs.tag }}
    steps:
      - name: "print debug"
        run: |
          echo ${{github.event.base_ref}}

      - name: "Release PR info"
        if: github.event_name != 'workflow_dispatch'
        run: echo "PR ${{ github.event.number }}"
      - uses: actions/checkout@v3

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      # java publish
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Extract tag version
        id: extract_tag
        run: echo "tag=$(echo ${{ github.ref }} | sed -e 's/^refs\/tags\/v//' -e 's/^refs\/heads\/v//')" >> "$GITHUB_OUTPUT"
      - name: Update pom.xml version
        # sed only version of project
        run: |
          sed -i "s/<projectVersion>.*<\/projectVersion>/<projectVersion>${{ steps.extract_tag.outputs.tag }}<\/projectVersion>/" pom.xml

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          PROFILE: dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: publish
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.publish.outputs.tag }}
