name: Release to github release
on:
  workflow_call:
#    with tag
    inputs:
      tag:
        description: 'tag'
        type: string
        required: true
        default: 'v0.0.0'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: "Release PR info"
        if: github.event_name != 'workflow_dispatch'
        run: echo "PR ${{ github.event.number }}"
      - uses: actions/checkout@v3
      ############# GITHUB RELEASE ##############
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1

      - name: "Create a GitHub release v${{ github.event.inputs.tag }}"
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ github.event.inputs.tag }}"
          name: "Release v${{ github.event.inputs.tag }}"
          body: |
            ## Release notes:
            ${{ steps.extract-release-notes.outputs.release_notes }}
